version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off
after_build:
    - cd
    - dir
    - 7z a -tzip BackVueDownloader.zip .\artifacts
artifacts:  
- path: BackVueDownloader.zip
  name: BackVueDownloader
deploy:
  release: 'v1.1.$(appveyor_build_version)'
  description: 'Release v1.1.$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: +L7awVOpkoS9AFH2iw1R84aEas7eGSFoR1MmKz285Svi8M2H3cSZ8h47bG9NRenw
  artifact: BackVueDownloader
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
